.PHONY: build test test-race integration fmt vet
build:
	go build -o bin/aero-arc-archive-worker ./cmd/aero-arc-archive-worker
test:
	go test ./...
test-race:
	go test -race ./...
integration:
	go test -tags=integration -timeout=10m ./...
fmt:
	gofmt -w cmd internal
vet:
	go vet ./...
	go vet -tags=integration ./...
